Lib.declare("EncounterMgr", {})
Lib.declare("RegionManager", {})
Lib.declare("RegionSafe", {})
Lib.declare("RegionHidePKM", {})
Lib.declare("RegionBrightPKM", {})
Lib.declare("RegionObstacle", {})
Lib.declare("SkillMgr", {})
Lib.declare("SkillEffectMgr", {})
Lib.declare("TeamMgr", {})
Lib.declare("DailyLotteryMgr", {})
Lib.declare("GloryHallMgr", {})
require("script_server.entity.entity")
require("script_server.entity.entity_event")
require("script_server.entity.entity_interaction")
require("script_server.entity.ai.ai_control")
require("script_server.entity.ai.ai_state_chase")
require("script_server.player.player")
require("script_server.player.player_event")
require("script_server.player.player_packet")
require("script_server.player.player_bag")
require("script_server.player.player_trigger_gift")
require("script_server.player.player_recharge")
require("script_server.player.player_pokemon_swap")
require("script_server.player.player_rank")
require("script_server.player.player_glory_hall")
require("script_server.trigger_handlers")
require("script_server.player.player_new_design")
require("script_server.scene.glory_hall_manager")
require("script_server.scene.encounter.encounter_mgr")
require("script_server.world.region")
require("script_server.world.region_manager")
require("script_server.world.region.region_safe")
require("script_server.world.region.region_hide_pkm")
require("script_server.world.region.region_bright_pkm")
require("script_server.world.region.region_obstacle")
require("script_server.skill.skill")
require("script_server.skill.timeLine")
require("script_server.skill.click")
require("script_server.skill.skill_mgr")
require("script_server.skill.skill_effect_mgr")
require("script_server.missile.missile_server")
require("script_server.shop.shop_manager")
require("script_server.shop.regular_gift_shop")
require("script_server.game.game")
require("script_server.team.team_mgr")
local RedisHandler = require("script_server.redishandler")
RedisHandler:init()
require("script_server.rank")
require("script_server.reward.lucky_egg_award")
require("script_server.reward.daily_lottery_mgr")
require("script_server.reward.rotary_table_award")
require("script_server.async_process.async_process")
require("script_server.async_process.highlight_data_handler")
require("script_server.redishandler")
local main = {}
local roomGameConfig = Server.CurServer:getConfig()

function main:init()
  self:setGlobalProperty()
  self:initLog()
  self:loadConfig()
  local BattleFieldManager = require("script_server.battle.battle_field_manager")
  BattleFieldManager:init()
  local PokemonManager = require("script_server.pokemon.pokemon_manager")
  PokemonManager:init()
  RegionManager:init()
  math.randomseed(tostring(os.time()):reverse():sub(1, 7))
  EncounterMgr:init()
  SkillEffectMgr:init()
  DailyLotteryMgr:init()
  GloryHallMgr:init()
end

function main:setGlobalProperty()
  GlobalProperty.Instance():setBoolProperty("DisableCheckBlockTouch", true)
end

function main:initLog()
  Lib.setDebugLog(roomGameConfig:isDebug())
end

function main:loadConfig()
  local PokemonRotaryTableConfig = T(Config, "PokemonRotaryTableConfig")
  PokemonRotaryTableConfig:init()
  local PokemonGloryHallConfig = T(Config, "PokemonGloryHallConfig")
  PokemonGloryHallConfig:init()
  local MainUiMenuBtnConfig = T(Config, "MainUiMenuBtnConfig")
  MainUiMenuBtnConfig:init()
  local PokemonLuckyRareConfig = T(Config, "PokemonLuckyRareConfig")
  PokemonLuckyRareConfig:init()
  local PokemonLuckyPriceConfig = T(Config, "PokemonLuckyPriceConfig")
  PokemonLuckyPriceConfig:init()
  local PokemonLuckyPkmConfig = T(Config, "PokemonLuckyPkmConfig")
  PokemonLuckyPkmConfig:init()
  local PokemonLuckyExtraConfig = T(Config, "PokemonLuckyExtraConfig")
  PokemonLuckyExtraConfig:init()
  local TriggerGiftConfig = T(Config, "TriggerGiftConfig")
  TriggerGiftConfig:init()
  local RegularGiftItemConfig = T(Config, "RegularGiftItemConfig")
  RegularGiftItemConfig:init()
  local RegularGiftConfig = T(Config, "RegularGiftConfig")
  RegularGiftConfig:init()
  local RechargeAwardConfig = T(Config, "RechargeAwardConfig")
  RechargeAwardConfig:init()
  local WorldCommonTipsConfig = T(Config, "WorldCommonTipsConfig")
  WorldCommonTipsConfig:init()
  local WorldCommonTipsConfig = T(Config, "WorldCommonTipsConfig")
  WorldCommonTipsConfig:init()
  local PayShopConfig = T(Config, "PayShopConfig")
  PayShopConfig:init()
  local SoundConfig = T(Config, "SoundConfig")
  SoundConfig:init()
  local GloryConfig = T(Config, "GloryConfig")
  GloryConfig:init()
  local PlayerExpConfig = T(Config, "PlayerExpConfig")
  PlayerExpConfig:init()
  local NormalBattleRewardConfig = T(Config, "NormalBattleRewardConfig")
  NormalBattleRewardConfig:init()
  local MainBattleRewardConfig = T(Config, "MainBattleRewardConfig")
  MainBattleRewardConfig:init()
  local SpriteBallConfig = T(Config, "SpriteBallConfig")
  SpriteBallConfig:init()
  local SkillConfig = T(Config, "SkillConfig")
  SkillConfig:init()
  local SkillEffectConfig = T(Config, "SkillEffectConfig")
  SkillEffectConfig:init()
  local NPCConfig = T(Config, "NPCConfig")
  NPCConfig:init()
  local NPCPokemonConfig = T(Config, "NPCPokemonConfig")
  NPCPokemonConfig:init()
  local PokemonLeaderboardRewardConfig = T(Config, "PokemonLeaderboardRewardConfig")
  PokemonLeaderboardRewardConfig:init()
  local MapConfig = T(Config, "MapConfig")
  MapConfig:init()
  local RegionConfig = T(Config, "RegionConfig")
  RegionConfig:init()
  local GymConfig = T(Config, "GymConfig")
  GymConfig:init()
  local GymDefaultRankConfig = T(Config, "GymDefaultRankConfig")
  GymDefaultRankConfig:init()
  local PokemonGuideConfig = T(Config, "PokemonGuideConfig")
  PokemonGuideConfig:init()
  local SkillPerformConfig = T(Config, "SkillPerformConfig")
  SkillPerformConfig:init()
  local ActiveRewardConfig = T(Config, "ActiveRewardConfig")
  ActiveRewardConfig:init()
  local PokemonTaskConfig = T(Config, "PokemonTaskConfig")
  PokemonTaskConfig:init()
  local DailyLotteryConfig = T(Config, "DailyLotteryConfig")
  DailyLotteryConfig:init()
  local CheatConfig = T(Config, "CheatConfig")
  CheatConfig:init()
end

main:init()
