Event.EVENT_UPDATE_HOUSE_INFO = Event.register("EVENT_UPDATE_HOUSE_INFO")
if World.isClient then
  Event.EVENT_UPDATE_OWN_HOUSE_BGM = Event.register("EVENT_UPDATE_OWN_HOUSE_BGM")
  Event.EVENT_SHOW_OPERATION_PANEL = Event.register("EVENT_SHOW_OPERATION_PANEL")
  Event.EVENT_REMOVE_OPERATION_PANEL = Event.register("EVENT_REMOVE_OPERATION_PANEL")
  Event.EVENT_RECEIVE_HOUSE_INFO = Event.register("EVENT_RECEIVE_HOUSE_INFO")
  Event.EVENT_UPDATE_DISASTER_SELECT = Event.register("EVENT_UPDATE_DISASTER_SELECT")
  Event.EVENT_UPDATE_DISASTER_CD = Event.register("EVENT_UPDATE_DISASTER_CD")
  Event.EVENT_OPERATION_PANEL_VISIBLE = Event.register("EVENT_OPERATION_PANEL_VISIBLE")
else
end
