if World.isClient then
  Event.EVENT_UPDATE_CLIENT_BAG_INFO = Event.register("EVENT_UPDATE_CLIENT_BAG_INFO")
  Event.EVENT_UPDATE_HAND_BAG_INFO = Event.register("EVENT_UPDATE_HAND_BAG_INFO")
  Event.EVENT_REMOVE_HAND_BAG_INFO = Event.register("EVENT_REMOVE_HAND_BAG_INFO")
  Event.EVENT_UPDATE_IN_USE_PROP = Event.register("EVENT_UPDATE_IN_USE_PROP")
  Event.EVENT_UPDATE_UNLOCK_PROP = Event.register("EVENT_UPDATE_UNLOCK_PROP")
  Event.EVENT_UPDATE_BILLBOARD_SHOW = Event.register("EVENT_UPDATE_BILLBOARD_SHOW")
  Event.EVENT_UPDATE_BILLBOARD_INFO = Event.register("EVENT_UPDATE_BILLBOARD_INFO")
  Event.EVENT_UPDATE_SHOP_CAR_NAME = Event.register("EVENT_UPDATE_SHOP_CAR_NAME")
else
end
