---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/20 22:52
---

GM.isOpen = true
World.gameCfg.gm = true

local LuaHookProfiler = T(Lib, "LuaHookProfiler")
require("script_common.define")
require("script_common.event_define")
require("script_common.config.pokemon_rotary_table_config")
require("script_common.config.pokemon_glory_hall_config")
require("script_common.config.main_ui_menu_btn_config")
require("script_common.config.pokemon_lucky_rare_config")
require("script_common.config.pokemon_lucky_price_config")
require("script_common.config.pokemon_lucky_pkm_config")
require("script_common.config.pokemon_lucky_extra_config")
require("script_common.config.trigger_gift_config")
require("script_common.config.regular_gift_item_config")
require("script_common.config.regular_gift_config")
require("script_common.config.rechargeAward_config")
require("script_common.config.world_common_tips_config")
require("script_common.config.world_common_tips_config")
require("script_common.config.pay_shop_config")
require("script_common.config.glory_config")
require("script_common.config.sprite_ball_config")
require("script_common.config.pokemon_config")
require("script_common.config.skill_config")
require("script_common.config.skill_effect_config")
require("script_common.config.player_exp_config")
require("script_common.config.race_config")
require("script_common.config.main_battle_reward_config")
require("script_common.config.normal_battle_reward_config")
require("script_common.config.wash_cost_config")
require("script_common.config.bless_item_config")
require("script_common.config.sound_config")
require("script_common.config.npc_config")
require("script_common.config.npc_pokemon_config")
require("script_common.config.map_config")
require("script_common.config.region_config")
require("script_common.config.gym_config")
require("script_common.config.gym_default_rank_config")
require("script_common.config.active_reward_config")
require("script_common.config.pokemon_guide_config")
require("script_common.config.pokemon_task_config")
require("script_common.config.pokemon_leaderboard_reward_config")
require("script_common.config.cheat_config")
require("script_common.config.skill_perform_config")
require("script_common.config.daily_lottery_config")
require("script_common.entity")
require("script_common.map")
require("script_common.lib")
require("script_common.limited_time_activity_game_mgr")
require("script_common.subscribe_vip_helper")
require("common.gm")
if PlatformUtil.isPlatformWindows() then
  LogUtil.setMaxMessageSize(102400)
end
require("script_common.packet_convert")
if World.isClient then
  require("script_client.main")
else
  require("script_server.main")
end
