if World.isClient then
  Event.EVENT_PET_CARRY_CHANGE = Event.register("EVENT_PET_CARRY_CHANGE")
  Event.EVENT_PET_CARRY_OBJ_ID_CHANGE = Event.register("EVENT_PET_CARRY_OBJ_ID_CHANGE")
  Event.EVENT_PEAK_DAY_PET_RECEIVED = Event.register("EVENT_PEAK_DAY_PET_RECEIVED")
  Event.EVENT_PET_RIDE_STATUS_CHANGE = Event.register("EVENT_PET_RIDE_STATUS_CHANGE")
  Event.EVENT_OPEN_PET_NAME_SETTING = Event.register("EVENT_OPEN_PET_NAME_SETTING")
else
end
