if World.isClient then
  Event.BIDDING_LOADED_RANK_LIST = Event.register("BIDDING_LOADED_RANK_LIST")
  Event.BIDDING_LOADED_RANK_NUM = Event.register("BIDDING_LOADED_RANK_NUM")
  Event.BIDDING_LOADED_PLAYER_NAME = Event.register("BIDDING_LOADED_PLAYER_NAME")
  Event.BIDDING_RANK_INFO_LOADED = Event.register("BIDDING_RANK_INFO_LOADED")
  Event.BIDDING_LOADED_AUDIT_RANK_LIST = Event.register("BIDDING_LOADED_AUDIT_RANK_LIST")
  Event.BIDDING_AUDIT_SUCCESS = Event.register("BIDDING_AUDIT_SUCCESS")
  Event.BIDDING_LOADED_AUDIT_MAP_INFO = Event.register("BIDDING_LOADED_AUDIT_MAP_INFO")
  Event.UPDATE_BIDDING_RECOMMEND_INFO = Event.register("UPDATE_BIDDING_RECOMMEND_INFO")
  Event.UPDATE_BIDDING_MY_INFO = Event.register("UPDATE_BIDDING_MY_INFO")
  Event.UPDATE_BIDDING_RECOMMEND_UP = Event.register("UPDATE_BIDDING_RECOMMEND_UP")
else
  Event.BIDDING_ASYNC_RANK_NUM = Event.register("BIDDING_ASYNC_RANK_NUM")
  Event.BIDDING_ASYNC_RANK_LIST_DATA = Event.register("BIDDING_ASYNC_RANK_LIST_DATA")
end
