if World.isClient then
  Event.EVENT_FRIEND_UPDATE_STATUS = Event.register("EVENT_FRIEND_UPDATE_STATUS")
  Event.EVENT_FRIEND_UPDATE_RED_NUM = Event.register("EVENT_FRIEND_UPDATE_RED_NUM")
  Event.EVENT_UPDATE_FRIEND_TIP = Event.register("EVENT_UPDATE_FRIEND_TIP")
  Event.EVENT_UPDATE_NEAR_PLAYER = Event.register("EVENT_UPDATE_NEAR_PLAYER")
else
end
