if World.isClient then
  Event.EVENT_PROFESSION_UPDATE_HEAD_NAME = Event.register("EVENT_PROFESSION_UPDATE_HEAD_NAME")
  Event.EVENT_PROFESSION_UPDATE_HEAD_INTRODUCE = Event.register("EVENT_PROFESSION_UPDATE_HEAD_INTRODUCE")
  Event.EVENT_PROFESSION_UPDATE_CAREER = Event.register("EVENT_PROFESSION_UPDATE_CAREER")
  Event.EVENT_UPDATE_ALL_CAREER_DATA = Event.register("EVENT_UPDATE_ALL_CAREER_DATA")
  Event.EVENT_UPDATE_PHONE_CALL_ICON = Event.register("EVENT_UPDATE_PHONE_CALL_ICON")
  Event.EVENT_PROFESSION_WIN_OPEN = Event.register("EVENT_PROFESSION_WIN_OPEN")
else
end
