if World.isClient then
  Event.EVENT_HELICOPTER_UP_LIFT_OVER = Event.register("EVENT_HELICOPTER_UP_LIFT_OVER")
  Event.EVENT_UPDATE_IN_USE_CAR = Event.register("EVENT_UPDATE_IN_USE_CAR")
  Event.EVENT_DRIVE_ADVANCED_CAR = Event.register("EVENT_DRIVE_ADVANCED_CAR")
  Event.EVENT_CAR_STATUS_CHANGE = Event.register("EVENT_CAR_STATUS_CHANGE")
  Event.EVENT_CAR_BGM_UPDATE = Event.register("EVENT_CAR_BGM_UPDATE")
  Event.EVENT_CAR_CREATED = Event.register("EVENT_CAR_CREATED")
  Event.EVENT_CAR_CREATE_CD_UPDATE = Event.register("EVENT_CAR_CREATE_CD_UPDATE")
else
end
