Define.PART_INTERACT_TYPE = {
  CLICKED = 1,
  TOUCH_BEGIN = 2,
  TOUCH_END = 3,
  POP_CLICKED = 4,
  PART_TOUCH_PART_BEGIN = 5,
  PART_TOUCH_PART_END = 6,
  GAME_TIME = 7,
  PART_SPAWN = 8,
  FORCE_TRIGGER = 9
}
