Define.LIMITED_TIME_ACTIVITY_STATUS = {
  NOT_START = 0,
  START = 1,
  END = 2
}
Define.LIMITED_TIME_ACTIVITY_TYPE = {
  LIMITED_TIME_DRAW = 1,
  MUST_WIN_LOTTERY = 2,
  COMBINATION_GIFT = 3,
  SIGNAL_GIFT = 4,
  MONTH_GIFT = 5,
  WEEK_GIFT = 6,
  DISCOUNT = 7,
  LIMITED_TIME_CARD = 8,
  OPTIONAL_GIFT = 9,
  LIMITED_TIME_GOLD_WHEEL = 10,
  HEART_WARM_GIFT = 11
}
Define.LIMITED_TIME_ACTIVITY_WND = {COMMON_WND = 1}
Define.LIMITED_TIME_ACTIVITY_MENU = {
  LIMITED_TIME_ACTIVITY = 1,
  COMBINATION_GIFT = 2,
  SIGNAL_GIFT = 3
}
Define.LUCKY_DRAW_TYPE = {SINGLE = 1, TEN = 2}
Define.LIMITED_TIME_ACTIVITY_COMMON_DIALOG_TYPE = {
  TEXT = 1,
  POND = 2,
  QUESTION = 3
}
Define.LIMITED_TIME_CARD = {WEEK = 1, MONTH = 2}
Define.HEART_WARM_TASK_TYPE = {
  ADD_FRIEND = 1,
  PROFESSION = 2,
  CHANGE_DRESS = 3,
  NEW_HOUSE = 4,
  CAR_OTHERS = 5,
  GIFT_OTHERS = 6,
  INTERACT = 7,
  FIRE_HOUSE = 8,
  POLICE_LOCK = 9,
  PUT_OUT_FIRE = 10,
  ALL_FINISH = 11
}
Define.HEART_WARM_TASK_STATE = {
  NOT_START = 1,
  START = 2,
  FINISH = 3,
  END = 4
}
