if World.isClient then
  Event.EVENT_DRAMA_CONTENT_UPDATE = Event.register("EVENT_DRAMA_CONTENT_UPDATE")
  Event.EVENT_DRAMA_UPDATE_WND_INFO = Event.register("EVENT_DRAMA_UPDATE_WND_INFO")
  Event.EVENT_DRAMA_UPDATE_LIKES_NUM = Event.register("EVENT_DRAMA_UPDATE_LIKES_NUM")
  Event.EVENT_DRAMA_LIKE_RANKING_UPDATE = Event.register("EVENT_DRAMA_LIKE_RANKING_UPDATE")
  Event.EVENT_DRAMA_HISTORY_UPDATE = Event.register("EVENT_DRAMA_HISTORY_UPDATE")
  Event.EVENT_DRAMA_SELECT_COVER = Event.register("EVENT_DRAMA_SELECT_COVER")
  Event.EVENT_DRAMA_UPDATE_CREATE_ITEM = Event.register("EVENT_DRAMA_UPDATE_CREATE_ITEM")
  Event.EVENT_DRAMA_UPDATE_ROLE_ITEM_NAME = Event.register("EVENT_DRAMA_UPDATE_ROLE_ITEM_NAME")
  Event.EVENT_DRAMA_UPDATE_CREATE_INFO = Event.register("EVENT_DRAMA_UPDATE_CREATE_INFO")
  Event.EVENT_DRAMA_UPDATE_DETAIL_INFO = Event.register("EVENT_DRAMA_UPDATE_DETAIL_INFO")
  Event.EVENT_DRAMA_UPDATE_CUR_DETAIL = Event.register("EVENT_DRAMA_UPDATE_CUR_DETAIL")
  Event.EVENT_DRAMA_THUMB_UP_RESULT = Event.register("EVENT_DRAMA_THUMB_UP_RESULT")
  Event.EVENT_DRAMA_UPDATE_LIKE_INF = Event.register("EVENT_DRAMA_UPDATE_LIKE_INF")
else
end
