Define.GAME_MODE = {
  NONE = 0,
  EDIT = 1,
  PLAY = 2
}
Define.MOD_INTERVAL = {
  NONE = 0,
  GEOMETRY = 0.5,
  PROP = 0.25
}
Define.MATERIAL_ATTRIBUTE = {
  NONE = 0,
  WATER = 1,
  GLASS = 2
}
Define.LIGHT_TYPE = {
  NONE = 0,
  AMBIENT = 1,
  DIFFUSE = 2,
  SPECULAR = 3
}
Define.RAY_CAST_TYPE = {
  EMPTY = 0,
  BLOCK = Bitwise64.Sl(1, 0),
  ENTITY = Bitwise64.Sl(1, 1),
  DROPITEM = Bitwise64.Sl(1, 2),
  PART = Bitwise64.Sl(1, 3),
  INSTANCE = Bitwise64.Sl(1, 4),
  TERRAIN = Bitwise64.Sl(1, 5),
  OBJECT = Bitwise64.And(4294967295, Bitwise64.Not(Bitwise64.Sl(1, 0))),
  ALL = 4294967295
}
Define.ABILITY_EDITOR = {
  TRANSLATE = Bitwise64.Sl(1, 1),
  SCALE = Bitwise64.Sl(1, 2),
  ROTATE = Bitwise64.Sl(1, 3),
  TRANSFORM = Bitwise64.Or(Bitwise64.Sl(1, 1), Bitwise64.Sl(1, 2), Bitwise64.Sl(1, 3)),
  AABB = Bitwise64.Sl(1, 4),
  DUPLICATE = Bitwise64.Sl(1, 5),
  GROUP = Bitwise64.Sl(1, 6),
  FOCUS = Bitwise64.Sl(1, 7),
  MATERIAL = Bitwise64.Sl(1, 8),
  SELECTABLE = Bitwise64.Sl(1, 9),
  DELETE = Bitwise64.Sl(1, 10),
  UNGROUP = Bitwise64.Sl(1, 11)
}
Define.NODE_TYPE = {
  NONE = 0,
  PART = 1,
  MODEL = 2,
  MESHPART = 3,
  REGIONPART = 4,
  PARTOPERATION = 5
}
Define.CLASS_ABILITY_EDITOR = {
  [Define.NODE_TYPE.PARTOPERATION] = Bitwise64.Or(Define.ABILITY_EDITOR.TRANSFORM, Define.ABILITY_EDITOR.AABB, Define.ABILITY_EDITOR.FOCUS, Define.ABILITY_EDITOR.SELECTABLE, Define.ABILITY_EDITOR.DUPLICATE, Define.ABILITY_EDITOR.DELETE, Define.ABILITY_EDITOR.GROUP, Define.ABILITY_EDITOR.MATERIAL),
  [Define.NODE_TYPE.PART] = Bitwise64.Or(Define.ABILITY_EDITOR.TRANSFORM, Define.ABILITY_EDITOR.AABB, Define.ABILITY_EDITOR.FOCUS, Define.ABILITY_EDITOR.SELECTABLE, Define.ABILITY_EDITOR.DUPLICATE, Define.ABILITY_EDITOR.DELETE, Define.ABILITY_EDITOR.GROUP, Define.ABILITY_EDITOR.MATERIAL),
  [Define.NODE_TYPE.MODEL] = Bitwise64.Or(Define.ABILITY_EDITOR.TRANSFORM, Define.ABILITY_EDITOR.AABB, Define.ABILITY_EDITOR.FOCUS, Define.ABILITY_EDITOR.SELECTABLE, Define.ABILITY_EDITOR.DUPLICATE, Define.ABILITY_EDITOR.DELETE, Define.ABILITY_EDITOR.GROUP, Define.ABILITY_EDITOR.UNGROUP),
  [Define.NODE_TYPE.MESHPART] = Bitwise64.Or(Define.ABILITY_EDITOR.TRANSFORM, Define.ABILITY_EDITOR.AABB, Define.ABILITY_EDITOR.FOCUS, Define.ABILITY_EDITOR.SELECTABLE, Define.ABILITY_EDITOR.DUPLICATE, Define.ABILITY_EDITOR.DELETE, Define.ABILITY_EDITOR.GROUP),
  [Define.NODE_TYPE.REGIONPART] = Bitwise64.Or(Define.ABILITY_EDITOR.TRANSLATE, Define.ABILITY_EDITOR.SCALE, Define.ABILITY_EDITOR.AABB, Define.ABILITY_EDITOR.FOCUS, Define.ABILITY_EDITOR.SELECTABLE, Define.ABILITY_EDITOR.DUPLICATE, Define.ABILITY_EDITOR.DELETE, Define.ABILITY_EDITOR.GROUP)
}
Define.TRANSFORM_TYPE = {
  NONE = 0,
  TRANSLATE = 1,
  ROTATE = 2,
  SCALE = 3
}
Define.SPACE_MODE = {
  NONE = 0,
  LOCAL = 1,
  WORLD = 2
}
Define.ENV_TYPE = {
  NONE = 0,
  SKYBOX = 1,
  WEATHER = 2,
  LIGHT = 3,
  MUSIC = 4
}
Define.GRAPHICS_QUALITY = {
  LOW = 0,
  MID = 1,
  HIGH = 2
}
Define.GRAPHICS_SHADOW = {ON = 1, OFF = 2}
Define.SOUND_CHANNEL_GROUP = {BGM = 0, EFFECT = 1}
Define.EDITOR_MODE = {ON = 1, OFF = 2}
Define.UPDATE_MAP_TYPE = {NORMAL = 0, BIDDING = 1}
