if World.isClient then
  Event.EVENT_DANCE_ACTION_CLICK = Event.register("EVENT_DANCE_ACTION_CLICK")
  Event.EVENT_DANCE_ITEM_SHOW = Event.register("EVENT_DANCE_ITEM_SHOW")
  Event.EVENT_UPDATE_LOSE_CONTROL_GLASSES_UI = Event.register("EVENT_UPDATE_LOSE_CONTROL_GLASSES_UI")
  Event.EVENT_UPDATE_TELESCOPE_UI = Event.register("EVENT_UPDATE_TELESCOPE_UI")
  Event.EVENT_DANCE_ACTION_CANCEL = Event.register("EVENT_DANCE_ACTION_CANCEL")
  Event.EVENT_UPDATE_PREVIEW_PALETTE = Event.register("EVENT_UPDATE_PREVIEW_PALETTE")
  Event.EVENT_UPDATE_INTERACT_CLICK_SHOW = Event.register("EVENT_UPDATE_INTERACT_CLICK_SHOW")
else
end
