if World.isClient then
  Event.EVENT_ADVERTISEMENT_MODULE_ON_DRAW_RESULT = Event.register("ADVERTISEMENT_MODULE_ON_DRAW_RESULT")
  Event.EVENT_ADVERTISEMENT_MODULE_ON_LOCK_RESULT = Event.register("EVENT_ADVERTISEMENT_MODULE_ON_LOCK_RESULT")
else
end
