local class = require("common.3rd.middleclass.middleclass")
local singleton = require("common.3rd.middleclass.singleton")
local stateful = require("common.3rd.stateful.stateful")
local ConfigManager = class("ConfigManager")
ConfigManager:include(singleton)
T(MobileEditor, "ConfigManager", ConfigManager)
local CommandManager = class("CommandManager")
CommandManager:include(singleton)
T(MobileEditor, "CommandManager", CommandManager)
local InputManager = class("InputManager")
InputManager:include(singleton)
T(MobileEditor, "InputManager", InputManager)
local GizmoManager = class("GizmoManager")
GizmoManager:include(singleton)
T(MobileEditor, "GizmoManager", GizmoManager)
local CameraManager = class("CameraManager")
CameraManager:include(singleton)
CameraManager:include(stateful)
T(MobileEditor, "CameraManager", CameraManager)
local TargetManager = class("TargetManager")
TargetManager:include(singleton)
T(MobileEditor, "TargetManager", TargetManager)
local DataManager = class("DataManager")
DataManager:include(singleton)
T(MobileEditor, "DataManager", DataManager)
local GameManager = class("GameManager")
GameManager:include(singleton)
GameManager:include(stateful)
T(MobileEditor, "GameManager", GameManager)
local ModeManager = class("ModeManager")
ModeManager:include(singleton)
T(MobileEditor, "ModeManager", ModeManager)
require("common.manager.config_manager")
require("common.manager.command_manager")
require("common.manager.input_manager")
require("common.manager.gizmo_manager")
require("common.manager.camera_manager")
require("common.manager.target_manager")
require("common.manager.data_manager")
require("common.manager.game_manager")
require("common.manager.mode_manager")
